sudo: required
dist: trusty
language: scala

scala:
- 2.12.3
- 2.11.11

env:
- JDK=oraclejdk8
- JDK=openjdk8

addons:
  mariadb: '10.2'

before_script:
  - mysql -u root -e 'create database test_db;'
  - jdk_switcher use $JDK

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
