dist: xenial
language: scala

jdk:
  - openjdk8
  - openjdk11
scala:
  - 2.12.10
  - 2.13.1

addons:
  mariadb: '10.2'

before_script:
  - mysql -u root -e 'create database test_db;'

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
