sudo: false

language: scala

scala:
- 2.11.8

jdk:
- oraclejdk8

addons:
  mariadb: '10.1'

services:
  - mysql

before_script:
  - mysql -e 'create database test_db;'

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
